#!/bin/bash
echo 'Installing dependencies....'
sudo apt-get install -y ca-certificates curl gnupg && sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list && sudo apt-get update && sudo apt-get install -y nodejs npm
echo 'Dependencies Installed!'
# Define variables
URL="https://raw.githubusercontent.com/QKing-Official/PTB/refs/heads/main/ptb"
DEST="/usr/local/bin/ptb"
echo 'Installing PTB....'
# Download the file
sudo curl -L -o "$DEST" "$URL"

# Give execution permission
sudo chmod +x "$DEST"

echo "Downloaded and installed ptb to $DEST"
echo "You can now run it using: ptb"
